-- phpMyAdmin SQL Dump
-- version 4.5.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Oct 09, 2017 at 09:45 PM
-- Server version: 5.7.11
-- PHP Version: 5.6.19

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `pilipinas`
--

-- --------------------------------------------------------

--
-- Table structure for table `advertiser`
--

CREATE TABLE `advertiser` (
  `advertiser_id` int(20) NOT NULL,
  `name` varchar(100) NOT NULL,
  `locality` varchar(50) NOT NULL,
  `province` varchar(50) NOT NULL,
  `regions` varchar(10) NOT NULL,
  `number` varchar(11) NOT NULL,
  `tel` int(10) NOT NULL,
  `email` varchar(50) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `advertiser`
--

INSERT INTO `advertiser` (`advertiser_id`, `name`, `locality`, `province`, `regions`, `number`, `tel`, `email`) VALUES
(1, 'Mark Mercado', 'Kawit', 'Manila', '4a', '09178075904', 1, '05markmercado@gmail.com');

-- --------------------------------------------------------

--
-- Table structure for table `festival`
--

CREATE TABLE `festival` (
  `festival_id` int(20) NOT NULL,
  `name` text NOT NULL,
  `place_id` int(50) NOT NULL,
  `month` int(2) NOT NULL,
  `image` varchar(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `festival`
--

INSERT INTO `festival` (`festival_id`, `name`, `place_id`, `month`, `image`) VALUES
(1, 'Pagoda Festival', 1, 10, 'img/places/region_3/festival/3_2_1.jpg'),
(2, 'Masskara Festival', 2, 10, 'img/places/region_6/festival/6_2_2.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `place`
--

CREATE TABLE `place` (
  `place_id` int(50) NOT NULL,
  `name` varchar(100) NOT NULL,
  `description` text NOT NULL,
  `category` int(1) NOT NULL,
  `locality` varchar(50) NOT NULL,
  `province` varchar(50) NOT NULL,
  `region` varchar(10) NOT NULL,
  `rating` float NOT NULL,
  `rating_total` int(11) NOT NULL,
  `vote` int(10) NOT NULL,
  `image` varchar(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `place`
--

INSERT INTO `place` (`place_id`, `name`, `description`, `category`, `locality`, `province`, `region`, `rating`, `rating_total`, `vote`, `image`) VALUES
(1, 'Philippine Arena', 'The Philippine Arena is a multipurpose indoor arena at Ciudad de Victoria, a 140-hectare tourism enterprise zone in Bocaue and Santa Maria, Bulacan, Philippines.[8] With a maximum seating capacity of 51,898, the Philippine Arena is the world\'s largest indoor arena.[9] It is one of the centerpiece of the many centennial projects[10] of the Iglesia Ni Cristo (INC) for their centennial celebration on July 27, 2014.[11] The legal owner of the arena is the INC\'s educational institution, New Era University.[12]', 1, 'Santa Maria', 'Bulacan', '3', 5, 15, 3, 'img/places/region_3/place/3_1_1.jpg'),
(2, 'Caribbean Waterpark & Hotel', 'Situated right in the heart of the city of Bacolod, Caribbean Water Park and Resotel is a new resort with a complete hotel facilities. Located at Goldenfield Commercial Complex, it\'s an enchantment for all children to explore the ways of the pirates.', 1, 'Bacolod City', 'Negros Occidental', '6', 4.14286, 29, 7, 'img/places/region_6/place/6_1_2.jpg'),
(3, 'Banaue Rice Terraces', 'The Banaue Rice Terraces (Filipino: Hagdan-hagdang Palayan ng Banawe) are 2,000-year-old terraces that were carved into the mountains of Ifugao in the Philippines by ancestors of the indigenous people. They are frequenty called the "Eighth Wonder of the World". It is commonly thought that the terraces were built with minimal equipment, largely by hand. The terraces are located approximately 1500 metres (5000 ft) above sea level. They are fed by an ancient irrigation system from the rainforests above the terraces. It is said that if the steps were put end to end, it would encircle half the globe.\r\nLocals to this day still plant rice and vegetables on the terraces, although more and more younger Ifugaos do not find farming appealing, often opting for the more lucrative hospitality industry generated by the terraces[citation needed]. The result is the gradual erosion of the characteristic "steps", which need constant reconstruction and care. In 2010, a further problem was drought, with the terraces drying up completely in March of that year.', 3, 'Banaue', 'Ifugao', 'CAR', 5, 5, 1, 'img/places/car/place/car_1_3.jpg'),
(4, 'Chocolate Hills', 'The Chocolate Hills (Cebuano: Mga Bungtod sa Tsokolate; Filipino: Mga Tsokolateng Burol) are a geological formation in the Bohol province of the Philippines. There are at least 1,260 hills but there may be as many as 1,776 hills spread over an area of more than 50 square kilometres (20 sq mi). They are covered in green grass that turns brown (like chocolate) during the dry season, hence the name.\r\nThe Chocolate Hills is a famous tourist attraction of Bohol. They are featured in the provincial flag and seal to symbolize the abundance of natural attractions in the province. They are in the Philippine Tourism Authority\'s list of tourist destinations in the Philippines; they have been declared the country\'s third National Geological Monument and proposed for inclusion in the UNESCO World Heritage List', 3, 'Carmen', 'Bohol', '7', 2, 4, 2, 'img/places/region_7/place/7_1_4.jpg'),
(5, 'Puerto Princesa Subterranean River National Park', 'The Puerto Princesa Subterranean River National Park is a protected area of the Philippines located about 80 kilometres (50 mi) north of the city centre of Puerto Princesa, Palawan. The river is also called Puerto Princesa Underground River. The national park is located in the Saint Paul Mountain Range on the western coast of the island. It is bordered by St. Paul Bay to the north and the Babuyan River to the east. The City Government of Puerto Princesa has managed the National Park since 1992. The entrance to the subterranean river is a short hike or boat ride from the town Sabang.\r\nIn 2010, a group of environmentalists and geologists discovered that the underground river has a second floor, which means that there are small waterfalls inside the cave. They also found a cave dome measuring 300 m (980 ft) above the underground river, rock formations, large bats, a deep water hole in the river, more river channels, and another deep cave, as well as marine creatures and more. Deeper areas of the underground river are almost impossible to explore due to oxygen deprivation.[clarification needed]\r\nOn November 11, 2011, Puerto Princesa Underground River was provisionally chosen as one of the New7Wonders of Nature. This selection was officially confirmed on January 28, 2012.', 3, 'Puerto Princesa', 'Palawan', '4b', 5, 10, 2, 'img/places/region_4b/place/4b_1_5.jpg'),
(7, 'Rizal Park', 'Rizal Park (Filipino: Liwasang Rizal), also known as Luneta Park or simply Luneta, is a historical urban park in the Philippines. Located along Roxas Boulevard, Manila, adjacent to the old walled city of Intramuros, it is one of the largest urban parks in Asia. It has been a favorite leisure spot, and is frequented on Sundays and national holidays. Rizal Park is one of the major tourist attractions of Manila.\r\nSituated by the Manila Bay, it is an important site in Philippine history. The execution of national hero José Rizal on December 30, 1896 fanned the flames of the 1896 Philippine Revolution against the Kingdom of Spain. The area was officially renamed Rizal Park in his honor, and the monument enshrining his remains serves as the park\'s symbolic focal point. The Declaration of Philippine Independence from the United States was held here on July 4, 1946 as were later political rallies including those of Ferdinand Marcos and Corazon Aquino in 1986 that culminated in the EDSA Revolution.', 2, 'Ermita', 'Manila', 'NCR', 4, 4, 1, 'img/places/ncr/place/ncr_1_7.jpg'),
(8, 'Mayon Volcano', 'Mayon (Central Bikol: Bulkan Mayon, Filipino: Bulkang Mayon), also known as Mayon Volcano or Mount Mayon, is an active stratovolcano in the province of Albay in Bicol Region, on the large island of Luzon in the Philippines. Renowned as the "perfect cone" because of its symmetric conical shape, the volcano and its surrounding landscape was declared a national park on July 20 of 1938, the first in the nation. It was reclassified a Natural Park and renamed as the Mayon Volcano Natural Park in 2000.[3] Local folklore refers to the volcano being named after the legendary princess-heroine Daragang Magayon (English: Beautiful Lady).[4]', 0, 'Legazpi', 'Albay', '5', 5, 15, 3, 'img/places/region_5/place/5_1_8.jpg'),
(9, 'Vigan City', 'Vigan , officially the City of Vigan, is a 4th class component city and capital of the province of Ilocos Sur, Philippines. According to the 2015 census, it has a population of 53,879 people.[3]\r\nLocated on the western coast of the large island of Luzon, facing the South China Sea, is a UNESCO World Heritage Site in that it is one of the few towns left in the Philippines whose old structures have mostly remained intact, and it is well known for its cobblestone streets and a unique architecture of the Philippine colonial era which fuses Native Philippine and Oriental building designs and construction, with colonial Spanish architecture. Former Philippine president Elpidio Quirino, the sixth President of the Philippines, was born in Vigan, at the former location of the Provincial Jail (his father was a warden); he resided in the Syquia Mansion.', 2, 'Vigan City', 'Ilocus Sur', '1', 4, 0, 2, 'img/places/region_1/place/1_1_9.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `product`
--

CREATE TABLE `product` (
  `product_id` int(20) NOT NULL,
  `name` varchar(50) NOT NULL,
  `description` text NOT NULL,
  `province` varchar(255) NOT NULL,
  `business_license_no` int(10) NOT NULL,
  `advertiser_id` int(20) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `product`
--

INSERT INTO `product` (`product_id`, `name`, `description`, `province`, `business_license_no`, `advertiser_id`) VALUES
(1, 'Team Manila Fashion', 'Filipino-design clothes and merchandise ', 'Manila', 123456, 1);

-- --------------------------------------------------------

--
-- Table structure for table `product_request`
--

CREATE TABLE `product_request` (
  `request_id` int(20) NOT NULL,
  `name` varchar(50) NOT NULL,
  `description` text NOT NULL,
  `place_id` int(50) NOT NULL,
  `business_license_no` int(10) NOT NULL,
  `advertiser_id` int(20) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `advertiser`
--
ALTER TABLE `advertiser`
  ADD PRIMARY KEY (`advertiser_id`);

--
-- Indexes for table `festival`
--
ALTER TABLE `festival`
  ADD PRIMARY KEY (`festival_id`);

--
-- Indexes for table `place`
--
ALTER TABLE `place`
  ADD PRIMARY KEY (`place_id`);

--
-- Indexes for table `product`
--
ALTER TABLE `product`
  ADD PRIMARY KEY (`product_id`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
